Front-SF-31
ichepkov2401/SimpleFuzzy pull request #12
Opened 2024-08-07 09:34 UTC by AlexSergy

2024-08-08 11:45 UTC, ichepkov2401 requested changes
В пустых изменениях нет смысла, если по дизайну менять ничего не надо. То просто без PR переводите задачу

2024-08-09 14:52 UTC, AlexSergy commented
Сделал дизайн чуть более подходящим под форму программы

2024-08-09 15:36 UTC, ichepkov2401 requested changes

2024-08-09 15:36 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/LoaderForm.cs
> +            if (treeView1.Nodes[2].Nodes.Count > 0 && Parent is MainWindow parent) parent.isContainSimulator = true;
Не совсем понимаю зачем здесь это изменение логики и как оно влияет на дизайн

2024-08-10 04:35 UTC, ichepkov2401 approved these changes

2024-08-10 04:35 UTC, merged