Commit№1
ichepkov2401/SimpleFuzzy pull request #22
Opened 2024-08-13 01:05 UTC by AlexSergy

2024-08-14 05:49 UTC, ichepkov2401 requested changes

2024-08-14 05:49 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.cs
> +        // Так как нынешний MoveMouse не может обрабатывать объекты типа ToolScriptItem, в этой сборке было решено адаптировать метод MouseMove
И оно работает?

2024-08-14 05:49 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.cs
> +        // Так как нынешний MoveMouse не может обрабатывать объекты типа ToolScriptItem, в этой сборке было решено адаптировать метод MouseMove
Если проблема только в нахождении объекта под курсором, зачем было менять логику ниже?

2024-08-15 21:15 UTC, ichepkov2401 requested changes

2024-08-16 12:15 UTC, AlexSergy commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmCreate.Designer.cs
> -            textBox2.Text = Directory.GetCurrentDirectory() + "\\Projects";
Прошу прощения, при тесте программы оно само почему-то меняется, сейчас исправлю

2024-08-17 10:37 UTC, ichepkov2401 requested changes

2024-08-17 10:37 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmSaveAs.Designer.cs
> +            textBox1.Text = "C:\\Users\\User\\AppData\\Local\\Microsoft\\VisualStudio\\17.0_09e0b232\\WinFormsDesigner\\ggkkb1md.ai3\\Projects";
Некорректное изменение

2024-08-20 10:35 UTC, ichepkov2401 approved these changes

2024-08-20 10:35 UTC, merged