SF-48
ichepkov2401/SimpleFuzzy pull request #35
Opened 2024-08-15 13:45 UTC by timofeyelin

https://etu-apu-9371.youtrack.cloud/issue/SF-48/Razrabotat-servis-rascheta-svojstv-nechetkogo-mnozhestva

2024-08-15 20:16 UTC, ichepkov2401 requested changes

2024-08-15 20:16 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.Model/LinguisticVariable.cs
> +        private object CalculateCore(IMembershipFunction term)
Скорее всего в требованиях допущена ошибка
![image](https://github.com/user-attachments/assets/51f7d38c-5678-44f4-9a40-ca815efb315e)
Скорее всего подразумевалось все подмножество элементов базового множества для которых значение функции принадлежности равно единице. Надо обратиться к аналитику за уточнением

2024-08-16 11:40 UTC, timofeyelin commented on SimpleFuzzy/SimpleFuzzy.Model/LinguisticVariable.cs
> +        private object CalculateCore(IMembershipFunction term)
Аналитик изменил условие и код был изменен

2024-08-17 10:26 UTC, ichepkov2401 approved these changes

2024-08-17 10:27 UTC, merged