SF-58
ichepkov2401/SimpleFuzzy pull request #49
Opened 2024-08-22 02:57 UTC by AlexSergy

2024-08-22 14:03 UTC, ichepkov2401 requested changes

2024-08-22 14:03 UTC, ichepkov2401 commented on SimpleFuzzy.ExampleModules/SimpleFuzzy.ExampleModules.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WinFormsApp1", "WinFormsApp1\WinFormsApp1.csproj", "{CA405FB8-2BA6-43C1-8C57-D1E592F86ACF}"
Это что?

2024-08-22 14:16 UTC, AlexSergy commented on SimpleFuzzy.ExampleModules/SimpleFuzzy.ExampleModules.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WinFormsApp1", "WinFormsApp1\WinFormsApp1.csproj", "{CA405FB8-2BA6-43C1-8C57-D1E592F86ACF}"
Тестировал, создав проект с формой, при удалении забыл про эту часть, сейчас исправлю

2024-08-22 14:38 UTC, MaxMen5 commented
У меня все равно картинка съехавшая (скрин в личку отправил)

2024-08-22 16:14 UTC, MaxMen5 approved these changes

2024-08-23 11:53 UTC, ichepkov2401 approved these changes

2024-08-23 11:53 UTC, merged