SF-24
ichepkov2401/SimpleFuzzy pull request #53
Opened 2024-08-22 19:47 UTC by damirbik

https://etu-apu-9371.youtrack.cloud/issue/SF-24/Vnedrenie-servisa-kompilyacii

2024-08-23 12:09 UTC, ichepkov2401 requested changes

2024-08-23 12:09 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.Abstract/ICompileService.cs
> +        public static SyntaxTree Parse(string text, string filename = "", CSharpParseOptions options = null)
А вызова метода парсинга предполагается, где-то за пределами класса компляции, если нет. То в интерефейсе его наверное описывать не нужно

2024-08-23 12:09 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.Service/CompileService.cs
> +        private static string runtimePath = @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{0}.dll";
Не уверен, что надо ссылаться на эти файлы (мы используем .NET, а здесь обращение к .NETFramework, а они в свою очередь не совместимы) + если нам нужно для компиляции dll, я предлагаю поставлять их в папке с программой вместе с приложением, а не надеется, что нужные файлы окажутся на компьютере у пользователя

2024-08-23 12:09 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.Service/CompileService.cs
> +                MetadataReference.CreateFromFile(string.Format(runtimePath, "System.Core"))
Возможно стоит добавить также SimpleFuzzy.Abstract.dll т.к. именно от туда реализуются интерфейсы модулей

2024-08-25 14:03 UTC, MaxMen5 commented
![Screenshot 2024-08-25 170257](https://github.com/user-attachments/assets/42fd2eef-3858-43e6-a24a-aec74c14bb32)
При генерации термов проставлять по умолчанию то же базовое множество, что было выбрано в окне фазификации

2024-08-25 14:04 UTC, MaxMen5 commented
![Screenshot 2024-08-25 170428](https://github.com/user-attachments/assets/8448b84d-770c-4a2d-b068-a0a0e8bf11e3)
Исправить ошибку приведения типов

2024-08-25 15:41 UTC, MaxMen5 approved these changes

2024-08-25 23:12 UTC, ichepkov2401 approved these changes

2024-08-25 23:13 UTC, merged