SF-62
ichepkov2401/SimpleFuzzy pull request #67
Opened 2024-08-26 15:17 UTC by timofeyelin

https://etu-apu-9371.youtrack.cloud/issue/SF-62/Dobavlenie-validacii-na-inputy-v-kotorye-ukazyvaetsya-put

2024-08-26 22:05 UTC, ichepkov2401 requested changes

2024-08-26 22:05 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/FilesPathsNamesValidator.cs
> +    public class FilesPathsNamesValidator
Выглядит хорошо, но давайте уберем всю статику и сделаем из этого сервис

2024-08-27 15:32 UTC, timofeyelin commented on SimpleFuzzy/SimpleFuzzy.View/FasificationForm.cs
> +                    if (!FilesPathsNamesValidator.IsValidFileName(variableName)||string.IsNullOrEmpty(variableName))
Ненужная проверка убрана

2024-08-28 15:18 UTC, ichepkov2401 requested changes
Сервис не зарегистрирован в Автофаке. Соответственно и подключать сервис для использования надо тоже через автофак

2024-08-29 23:48 UTC, ichepkov2401 requested changes

2024-08-29 23:48 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmSaveAs.cs
> +            IFilesPathsNamesValidator validator = new FilesPathsNamesValidatorService();
Инъекцию сервиса выполняем через автофак в конструкторе

2024-08-29 23:48 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmRename.cs
> +            IFilesPathsNamesValidator validator = new FilesPathsNamesValidatorService();
Инъекцию сервиса выполняем через автофак в конструкторе

2024-08-29 23:48 UTC, ichepkov2401 commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmCreate.cs
> +            IFilesPathsNamesValidator validator = new FilesPathsNamesValidatorService();
Инъекцию сервиса выполняем через автофак в конструкторе

2024-08-30 18:17 UTC, ichepkov2401 approved these changes

2024-08-30 18:17 UTC, merged