SF-77
ichepkov2401/SimpleFuzzy pull request #73
Opened 2024-08-27 15:46 UTC by Acrist671

2024-08-27 20:28 UTC, timofeyelin commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmOpen.cs
> -                    MessageBox.Show(ex.Message);
ConfirmOpen/listBox1_DoubleClick  не был удален

2024-08-27 20:32 UTC, timofeyelin requested changes
LoaderForm/OnButtonActionClick (Появляется при удалении сборки)
не был изменен

2024-08-27 21:17 UTC, Acrist671 commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmOpen.cs
> -                    MessageBox.Show(ex.Message);
так, вроде удален

2024-08-28 10:32 UTC, timofeyelin requested changes
ConfirmOpen/listBox1_DoubleClick не был удален

2024-08-28 11:26 UTC, timofeyelin approved these changes

2024-08-28 11:26 UTC, merged